[project]
name = "complexbuilder"
version = "0.0.1"
description = "module to build and predict protein multimer with AlphaFold"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["biopython", "matplotlib", "numpy>=2", "pandas"]

[tool.uv]
dev-dependencies = ["mypy", "notebook", "pytest", "ruff"]

[tool.ruff]
select = [
    "F", # Flake8
    "B", # Black
    "I", # isort
    "E", # error
    "W", # warning
]
ignore = []
exclude = [".ruff_cache", ".ruff.toml", ".ruff.lock"]
indent-width = 4
line-length = 88 # Same as Black.
target-version = "py311"
fixable = ["ALL"] # Allow fix for all enabled rules (when `--fix`) is provided.
unfixable = []

[tool.ruff.format]
quote-style = "double" # Like Black, use double quotes for strings.

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["complexbuilder"]
